/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bienestar_estudiantil;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.CheckBox;
import javax.sound.sampled.BooleanControl;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.eclipse.persistence.jpa.jpql.tools.ContentAssistProposals;

/**
 *
 * @author Eden
 */
public class MenuMaestro extends javax.swing.JFrame {

      /**
     * Creates new form MenuAlumno
     */
   
    public MenuMaestro() {
       
       initComponents();
       
       
    }
       public void busqueda_Asignatura(){
       Connection conn = null;     
       String   sql = null;
       ResultSet rs = null;
       Statement  st = null;
      
       
           try {
             
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bienestar_estudiantil","root","liberal");
              st = conn.createStatement();
              if (!(cb.getSelectedItem().toString()==null)){rs = st.executeQuery ("SELECT nombreAsignatura as  Asignatura FROM asignatura");} else {
                  rs = st.executeQuery ("SELECT nombreAsignatura as  Asignatura FROM asignatura where nombreAsignatura like '"+cb.getSelectedItem().toString()+"%' ");
           }
              
          while(rs.next()){
               String tmpStrObtenido = rs.getString("Asignatura");
               cb.addItem(tmpStrObtenido);
                               
                }
                
    
               
           
          conn.close();
         } catch (Exception e) {
             
             e.printStackTrace();
             return;
         }
        rs = null;
        st = null;
       try {
             
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bienestar_estudiantil","root","liberal");
              st = conn.createStatement();
              rs = st.executeQuery("SELECT nombreArea FROM Area");

            while(rs.next()){
               
               String tmpStrObtenido = rs.getString("nombreArea");
               
               ComboBox_Area.addItem(tmpStrObtenido);
               
               
           }
          conn.close();
         } catch (Exception e) {
             
             e.printStackTrace();
             return;
         }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtTelEmp = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        ComboBox_Area = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        lbMaestro = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        TxtIdemp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNombreEmp = new javax.swing.JTextField();
        TxtApellidoEmp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtDirEmp = new javax.swing.JTextField();
        TxtEmailEmp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_nuevo = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblFotoD = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_asig = new javax.swing.JTable();
        agrega_Asignatura = new javax.swing.JButton();
        Remueve_Asignatura = new javax.swing.JButton();
        cb = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Seleccion el Area del Docente:");

        jLabel6.setText("Ingrese Telefono del Docente:");

        TxtTelEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelEmpActionPerformed(evt);
            }
        });

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        ComboBox_Area.setToolTipText("");
        ComboBox_Area.setAction(ComboBox_Area.getAction());
        ComboBox_Area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_AreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        lbMaestro.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        lbMaestro.setText("Datos del Docente");

        jLabel1.setText("Ingrese No de Empleado:");

        TxtIdemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdempActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese Nombre del Docente:");

        jLabel3.setText("Ingrese Apellido del Docente:");

        jLabel4.setText("Ingrese Direccion del Docente:");

        TxtNombreEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreEmpActionPerformed(evt);
            }
        });

        TxtApellidoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApellidoEmpActionPerformed(evt);
            }
        });

        jLabel7.setText("Ingrese E-mail del Docente:");

        TxtDirEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDirEmpActionPerformed(evt);
            }
        });

        TxtEmailEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailEmpActionPerformed(evt);
            }
        });

        jLabel8.setText("Seleccion la Asignatura del Docente:");

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        lblFotoD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFotoD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/sorteo-de-pintura-icono-7347-128.png"))); // NOI18N
        lblFotoD.setToolTipText("");
        lblFotoD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoDMouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setLabelFor(lblFotoD);
        jLabel9.setText(" HAGA CLIC PARA CARGAR IMAGEN"); // NOI18N
        jLabel9.setAutoscrolls(true);
        jLabel9.setDoubleBuffered(true);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(lblFotoD, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 20, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblFotoD, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tb_asig.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Asignaturas"
            }
        ));
        tb_asig.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tb_asig);
        tb_asig.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        agrega_Asignatura.setText("+");
        agrega_Asignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agrega_AsignaturaActionPerformed(evt);
            }
        });

        Remueve_Asignatura.setText("-");
        Remueve_Asignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remueve_AsignaturaActionPerformed(evt);
            }
        });

        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(agrega_Asignatura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Remueve_Asignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TxtDirEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboBox_Area, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtTelEmp)
                                    .addComponent(TxtEmailEmp, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(TxtApellidoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtIdemp, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtIdemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtApellidoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtDirEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(TxtTelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(TxtEmailEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBox_Area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Remueve_Asignatura)
                                            .addComponent(agrega_Asignatura)
                                            .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_nuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_eliminar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(BtnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCancelar)))))
                .addContainerGap(307, Short.MAX_VALUE))
        );

        lbMaestro.getAccessibleContext().setAccessibleName("Datos del Maestro");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtTelEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelEmpActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed

        // TODO add your handling code here:
        limpiar();
        MenuPrincipal m = new MenuPrincipal();
        dispose();
        m.setVisible(true);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void ComboBox_AreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_AreaActionPerformed
     
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_AreaActionPerformed
File fichero= null;
    private void limpiar(){
    TxtIdemp.setText("");
    TxtNombreEmp.setText("");
    TxtApellidoEmp.setText("");
    TxtDirEmp.setText("");
    TxtEmailEmp.setText("");
    TxtTelEmp.setText("");
    lblFotoD.setIcon(null);
    }
    
    private void TxtIdempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdempActionPerformed

    private void TxtNombreEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreEmpActionPerformed

    private void TxtApellidoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApellidoEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApellidoEmpActionPerformed

    private void TxtDirEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDirEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDirEmpActionPerformed

    private void TxtEmailEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailEmpActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
    
        try {
            guardarCampos();
            limpiar();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMaestro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuMaestro.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        eliminar_maestro();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void lblFotoDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoDMouseClicked
        // TODO add your handling code here:
        foto();
    }//GEN-LAST:event_lblFotoDMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

        foto();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        foto();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void agrega_AsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agrega_AsignaturaActionPerformed
        // TODO add your handling code here:
        busqueda_Asignatura();
    }//GEN-LAST:event_agrega_AsignaturaActionPerformed

    private void Remueve_AsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remueve_AsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Remueve_AsignaturaActionPerformed
    boolean ima=false;
    void foto() {
       int resultado; 
        

        CargarFoto ventana = new CargarFoto();

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg","png");

        ventana.jfchCargarfoto.setFileFilter(filtro);

        resultado= ventana.jfchCargarfoto.showOpenDialog(null);

        if (JFileChooser.APPROVE_OPTION == resultado){

            fichero = ventana.jfchCargarfoto.getSelectedFile();

            try{

                ImageIcon icon = new ImageIcon(fichero.toString());

                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblFotoD.getWidth(), lblFotoD.getHeight(), Image.SCALE_DEFAULT));

                lblFotoD.setText(null);

                lblFotoD.setIcon( icono );
                
                ima=true;

            }catch(Exception ex){

                JOptionPane.showMessageDialog(null, "Error abriendo la imagen "+ ex);

            }

        }

    }
    void eliminar_maestro(){
        ConectarBD con= new ConectarBD();
        if (TxtIdemp.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Ingrese el numero de identidad del Catedratico a eliminar:");
            TxtIdemp.requestFocus();
        }else if(TxtIdemp.getText().length()!=13){
            JOptionPane.showMessageDialog(null, "Verificque el numero de identidad ejemplo(0301199102687)");
            TxtIdemp.requestFocus();	
        }else{
            long id=Long.parseLong(TxtIdemp.getText());
            String sql="delete from empleado where IdEmpleado="+id+"";
        try{  
            PreparedStatement ps= con.conexion().prepareCall(sql);
            int i=ps.executeUpdate();
            if(i==0){
                JOptionPane.showMessageDialog(null, "El Catedratico no fue eliminado");
            }else{
                JOptionPane.showMessageDialog(null, "El Catedratico fue eliminado Exitosamente");
                BtnGuardar.doClick();
                BtnCancelar.doClick();
            }    
            con.conexion().close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al eliminar chofer: " + e.getMessage());
        } 
        }
    }

 /* void buscar_c() throws IOException{
        if(TxtIdemp.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Ingrese un numero de identidad a buscar");
        }else if(TxtIdemp.getText().length()!=13){
            JOptionPane.showMessageDialog(null, "Ingrese un numero de identidad valido (0301199102687)");
            TxtIdemp.requestFocus();
        }
        else{
        long id=Long.parseLong(TxtIdemp.getText());
        modelo_tabla_chofer();
        String sql= "select *, (year(FROM_DAYS(DATEDIFF(NOW(), fecha_nacimiento)))) as edad "
                + "from chofer c "
                + "inner join empleado e on e.id_empleado=c.id_chofer "
                + "inner join persona p on p.id_persona=e.id_empleado "
                + "inner join sexo s on s.id_sexo=e.id_sexo "
                + "inner join estado_civil ec on ec.id_estado_civil=e.id_estado_civil "
                + "inner join tipo_licencia tl on tl.id_tipo_licencia=c.id_tipo_licencia "
                + "where id_chofer="+id+"";
        String []datos = new String [13];
        try{
            Statement st = con.conexion().createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            if (rs.getRow() == 0){
                modelo_tabla_chofer= new DefaultTableModel(); 
                tabla_chofer.setModel(modelo_tabla_chofer);
                JOptionPane.showMessageDialog(null,"No Existe");
            }else{
            do{
                datos[0]=rs.getString("id_persona");
                datos[1]=rs.getString("nombres");
                txt_nombres_chofer.setText(datos[1]);
                datos[2]=rs.getString("apellidos");
                txt_apellidos_chofer.setText(datos[2]);
                datos[3]=rs.getString("direccion");
                txt_direccion_chofer.setText(datos[3]);
                datos[4]=rs.getString("telefono");
                txt_telefono_chofer.setText(datos[4]);
                datos[5]=rs.getString("sexo");
                cmb_sexo_chofer.setSelectedIndex(rs.getInt("e.id_sexo")-1);
                datos[6]=rs.getString("estado_civil");
                cmb_estado_civil_chofer.setSelectedIndex(rs.getInt("e.id_estado_civil")-1);
                datos[7]=rs.getString("fecha_nacimiento");
                txt_fecha_nacimiento_chofer.setDate(rs.getDate("fecha_nacimiento"));
                datos[8]=rs.getString("edad");
                datos[9]=rs.getString("fecha_contratacion");
                txt_fecha_contratacion_chofer.setDate(rs.getDate("fecha_contratacion"));
                datos[10]=rs.getString("tipo_licencia");
                cmb_tipo_licencia_chofer.setSelectedIndex(rs.getInt("c.id_tipo_licencia")-1);
                datos[11]=rs.getString("sueldo");
                txt_sueldo_chofer.setText(datos[11]);
                datos[12]=rs.getBlob("foto").toString();
                Blob blob = rs.getBlob("foto");
                Image i= javax.imageio.ImageIO.read(blob.getBinaryStream());
                ImageIcon image = new ImageIcon(i);
                Icon icono = new ImageIcon(image.getImage().getScaledInstance(lbl_foto_chofer.getWidth(), 
                lbl_foto_chofer.getHeight(), Image.SCALE_DEFAULT));
                lbl_foto_chofer.setIcon(icono);
                lbl_foto_chofer.repaint();
                modelo_tabla_chofer.addRow(datos);
            }while(rs.next());
            con.conexion().close();}
            }catch (SQLException ex) {
                modelo_tabla_chofer= new DefaultTableModel(); 
                JOptionPane.showMessageDialog(null,"Erro al buscar chofer: "+ ex.getMessage());
            } }  
    */
  public boolean guardarCampos() throws  SQLException, ClassNotFoundException{
 String insert1 = "insert into empleado(idEmpleado, nombreEmpleado, apellidoEmpleado, telefonoEmpleado, dirEmpleado, eMailEmp,  fotoEmp) values(?,?,?,?,?,?,?)";
 String insert2 = "insert into catedratico(idEmpleado, idArea, idAsignatura) values(?,?,?)";
 FileInputStream fis1 = null;
 PreparedStatement ps = null;
 File file = fichero;
Class.forName("com.mysql.jdbc.Driver");
        Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/bienestar_estudiantil","root","liberal");
 try {
 conexion.setAutoCommit(false);
 
 
 ps = conexion.prepareStatement(insert1);
 
 ps.setString(1, TxtIdemp.getText());
 ps.setString(2, TxtNombreEmp.getText());
 ps.setString(3, TxtApellidoEmp.getText());
 ps.setString(4, TxtTelEmp .getText());
 ps.setString(5, TxtDirEmp.getText());
 ps.setString(6, TxtEmailEmp.getText());
 fis1 = new FileInputStream(file);
 ps.setBinaryStream(7,fis1,(int)file.length());
 ps.executeUpdate();
PreparedStatement ps1 = conexion.prepareStatement(insert2);
 ps1.setString(1, TxtIdemp.getText());
 ps1.setInt(2, ComboBox_Area.getSelectedIndex()+1);

 
 ps1.executeUpdate();
 conexion.commit();
JOptionPane.showMessageDialog(null, "Se ha Guardado el Registro exitosamente");   
return true;
 } catch (Exception ex) {
     
     Logger.getLogger(MySQL.class.getName()).log(Level.SEVERE, null, ex);
 }finally
 
 {
 try {
 ps.close();
 fis1.close();
 } catch (SQLException | IOException ex) {
 Logger.getLogger(MySQL.class.getName()).log(Level.SEVERE, null, ex);
 }
  
 }
        return false;
    } /*
     * @param args the command line arguments
     */
    
    public class ConectarBD {
    Connection con=null;
    public Connection conexion(){
        String usuario="root";
        String contraseña="liberal";
        String BD="bienestar_estudiantil";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/"+BD,usuario,contraseña);  
        }catch(ClassNotFoundException | SQLException e){           
            JOptionPane.showMessageDialog(null, "ERROR AL CONECTAR LA BASE DE DATOS: " + e.getMessage());
        }
        return con;        
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMaestro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JComboBox ComboBox_Area;
    private javax.swing.JButton Remueve_Asignatura;
    private javax.swing.JTextField TxtApellidoEmp;
    private javax.swing.JTextField TxtDirEmp;
    private javax.swing.JTextField TxtEmailEmp;
    private javax.swing.JTextField TxtIdemp;
    private javax.swing.JTextField TxtNombreEmp;
    private javax.swing.JTextField TxtTelEmp;
    private javax.swing.JButton agrega_Asignatura;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JComboBox cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label lbMaestro;
    private javax.swing.JLabel lblFotoD;
    private javax.swing.JTable tb_asig;
    // End of variables declaration//GEN-END:variables
}
