/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bienestar_estudiantil;

import Datos.operaciones;
import static bienestar_estudiantil.Denuncias.cb_tipo_denuncia_ge;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Eden
 */import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        mostrarCarrerasAlumno();
        mostrarTipoDenuncia();
        llenarCbMaestro();
        
    }
    private void limpiarAlumno(){
        Date myDate = new Date();
        ch_anio1.setSelected(false);
        ch_Lugar.setSelected(false);
        ch_carrera.setSelected(false);
       Jch_anio.setYear(Integer.parseInt(new SimpleDateFormat("yyyy").format(myDate)));
       txt_lugar.setText(null);
       cb_carrera.setSelectedIndex(0);
       Jch_anio.setEnabled(false);
       txt_lugar.setEnabled(false);
       cb_carrera.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Jpanel_reportes1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        Jpanel_reportes = new javax.swing.JTabbedPane();
        panel_Alumnos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_alumno = new javax.swing.JTable();
        ch_anio1 = new javax.swing.JCheckBox();
        ch_Lugar = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cb_carrera = new javax.swing.JComboBox();
        ch_carrera = new javax.swing.JCheckBox();
        btn_nueva_consulta = new javax.swing.JButton();
        btn_genR_al = new javax.swing.JButton();
        btn_salir_al = new javax.swing.JButton();
        txt_lugar = new javax.swing.JTextField();
        Jch_anio = new com.toedter.calendar.JYearChooser();
        panle_maestro = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_maestros = new javax.swing.JTable();
        txt_cat_nombre = new javax.swing.JTextField();
        ch_cat_nombre = new javax.swing.JCheckBox();
        btn_nueva_consulta_cat = new javax.swing.JButton();
        btn_genR_cat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_salir_c = new javax.swing.JButton();
        ComboBox_Area = new javax.swing.JComboBox();
        ch_Cate_Area = new javax.swing.JCheckBox();
        panelDenuncia = new javax.swing.JPanel();
        panel_denuncia = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_Denuncias = new javax.swing.JTable();
        ch_no_denuncia = new javax.swing.JCheckBox();
        btn_nueva_consulta2 = new javax.swing.JButton();
        btn_geneR_denun = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_salir_de = new javax.swing.JButton();
        ch_tipo_denuncia = new javax.swing.JCheckBox();
        cb_tipo_denuncia = new javax.swing.JComboBox();
        dch_rep_denuncia = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanel_reportes1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Jpanel_reportes1.addTab("Reportes Catedraticos", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        Jpanel_reportes1.addTab("Asignaturas", jPanel7);

        jButton2.setText("jButton1");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(151, 151, 151))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton2))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Jpanel_reportes1.addTab("Denuncias", jPanel8);

        Jpanel_reportes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tabla_alumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabla_alumno);

        ch_anio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ch_anio1.setText("Año de Ingreso");
        ch_anio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ch_anio1MousePressed(evt);
            }
        });

        ch_Lugar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ch_Lugar.setText("Lugar");
        ch_Lugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ch_LugarMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel1.setText("Panel de opciones para reporte ");

        cb_carrera.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Carrera" }));
        cb_carrera.setEnabled(false);
        cb_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_carreraActionPerformed(evt);
            }
        });

        ch_carrera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ch_carrera.setText("Carrera");
        ch_carrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ch_carreraMousePressed(evt);
            }
        });
        ch_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_carreraActionPerformed(evt);
            }
        });

        btn_nueva_consulta.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btn_nueva_consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new.png"))); // NOI18N
        btn_nueva_consulta.setText("Nueva Consulta");
        btn_nueva_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nueva_consultaActionPerformed(evt);
            }
        });

        btn_genR_al.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btn_genR_al.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/material.gif"))); // NOI18N
        btn_genR_al.setText("Generar Reporte");
        btn_genR_al.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genR_alActionPerformed(evt);
            }
        });

        btn_salir_al.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btn_salir_al.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door.png"))); // NOI18N
        btn_salir_al.setText("    Salir");
        btn_salir_al.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir_alActionPerformed(evt);
            }
        });

        txt_lugar.setEnabled(false);

        javax.swing.GroupLayout panel_AlumnosLayout = new javax.swing.GroupLayout(panel_Alumnos);
        panel_Alumnos.setLayout(panel_AlumnosLayout);
        panel_AlumnosLayout.setHorizontalGroup(
            panel_AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(panel_AlumnosLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panel_AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panel_AlumnosLayout.createSequentialGroup()
                        .addGroup(panel_AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_carrera, javax.swing.GroupLayout.Alignment.LEADING, 0, 164, Short.MAX_VALUE)
                            .addComponent(txt_lugar)
                            .addComponent(Jch_anio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_AlumnosLayout.createSequentialGroup()
                                .addGroup(panel_AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ch_anio1)
                                    .addComponent(ch_carrera))
                                .addGap(154, 154, 154)
                                .addGroup(panel_AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_genR_al, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(btn_nueva_consulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(52, 52, 52)
                                .addComponent(btn_salir_al, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ch_Lugar))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panel_AlumnosLayout.setVerticalGroup(
            panel_AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_AlumnosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panel_AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_AlumnosLayout.createSequentialGroup()
                        .addGroup(panel_AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ch_anio1)
                            .addComponent(Jch_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ch_Lugar)
                            .addComponent(txt_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_nueva_consulta))
                .addGap(35, 35, 35)
                .addGroup(panel_AlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch_carrera)
                    .addComponent(btn_genR_al)
                    .addComponent(btn_salir_al, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Jpanel_reportes.addTab("Reportes de Alumnos  ", panel_Alumnos);

        tabla_maestros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_maestros);

        txt_cat_nombre.setEnabled(false);

        ch_cat_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ch_cat_nombre.setText("Nombre");
        ch_cat_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ch_cat_nombreMousePressed(evt);
            }
        });

        btn_nueva_consulta_cat.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btn_nueva_consulta_cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new.png"))); // NOI18N
        btn_nueva_consulta_cat.setText("Nueva Consulta");
        btn_nueva_consulta_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nueva_consulta_catActionPerformed(evt);
            }
        });

        btn_genR_cat.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btn_genR_cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/material.gif"))); // NOI18N
        btn_genR_cat.setText("Generar Reporte");
        btn_genR_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genR_catActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel4.setText("Panel de opciones para reporte ");

        btn_salir_c.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btn_salir_c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door.png"))); // NOI18N
        btn_salir_c.setText("    Salir");
        btn_salir_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir_cActionPerformed(evt);
            }
        });

        ComboBox_Area.setToolTipText("");
        ComboBox_Area.setEnabled(false);

        ch_Cate_Area.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ch_Cate_Area.setText("Area");
        ch_Cate_Area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ch_Cate_AreaMousePressed(evt);
            }
        });
        ch_Cate_Area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_Cate_AreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panle_maestroLayout = new javax.swing.GroupLayout(panle_maestro);
        panle_maestro.setLayout(panle_maestroLayout);
        panle_maestroLayout.setHorizontalGroup(
            panle_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panle_maestroLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panle_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(panle_maestroLayout.createSequentialGroup()
                        .addGroup(panle_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_cat_nombre)
                            .addComponent(ComboBox_Area, javax.swing.GroupLayout.Alignment.LEADING, 0, 211, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(panle_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ch_cat_nombre)
                            .addComponent(ch_Cate_Area))))
                .addGap(162, 162, 162)
                .addGroup(panle_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panle_maestroLayout.createSequentialGroup()
                        .addComponent(btn_genR_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btn_salir_c, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_nueva_consulta_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(panle_maestroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
                .addContainerGap())
        );
        panle_maestroLayout.setVerticalGroup(
            panle_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panle_maestroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(panle_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nueva_consulta_cat)
                    .addComponent(txt_cat_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch_cat_nombre))
                .addGroup(panle_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panle_maestroLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panle_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_genR_cat)
                            .addComponent(btn_salir_c, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panle_maestroLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panle_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBox_Area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ch_Cate_Area))))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        Jpanel_reportes.addTab("Reportes Catedraticos   ", panle_maestro);

        tb_Denuncias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tb_Denuncias);

        ch_no_denuncia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ch_no_denuncia.setText("Fecha de Creacion");
        ch_no_denuncia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ch_no_denunciaMousePressed(evt);
            }
        });

        btn_nueva_consulta2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btn_nueva_consulta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new.png"))); // NOI18N
        btn_nueva_consulta2.setText("Nueva Consulta");
        btn_nueva_consulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nueva_consulta2ActionPerformed(evt);
            }
        });

        btn_geneR_denun.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btn_geneR_denun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/material.gif"))); // NOI18N
        btn_geneR_denun.setText("Generar Reporte");
        btn_geneR_denun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geneR_denunActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel3.setText("Panel de opciones para reporte ");

        btn_salir_de.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btn_salir_de.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door.png"))); // NOI18N
        btn_salir_de.setText("    Salir");
        btn_salir_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir_deActionPerformed(evt);
            }
        });

        ch_tipo_denuncia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ch_tipo_denuncia.setText("Tipo Denuncia");
        ch_tipo_denuncia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ch_tipo_denunciaMousePressed(evt);
            }
        });

        cb_tipo_denuncia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Tipo Denuncia" }));
        cb_tipo_denuncia.setEnabled(false);
        cb_tipo_denuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipo_denunciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_denunciaLayout = new javax.swing.GroupLayout(panel_denuncia);
        panel_denuncia.setLayout(panel_denunciaLayout);
        panel_denunciaLayout.setHorizontalGroup(
            panel_denunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_denunciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(panel_denunciaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panel_denunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(panel_denunciaLayout.createSequentialGroup()
                        .addGroup(panel_denunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_tipo_denuncia, 0, 165, Short.MAX_VALUE)
                            .addComponent(dch_rep_denuncia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(panel_denunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ch_tipo_denuncia, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ch_no_denuncia, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(166, 166, 166)
                .addGroup(panel_denunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_nueva_consulta2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_denunciaLayout.createSequentialGroup()
                        .addComponent(btn_geneR_denun, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salir_de, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panel_denunciaLayout.setVerticalGroup(
            panel_denunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_denunciaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addGroup(panel_denunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_denunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ch_no_denuncia)
                        .addComponent(btn_nueva_consulta2))
                    .addComponent(dch_rep_denuncia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel_denunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch_tipo_denuncia)
                    .addComponent(cb_tipo_denuncia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_geneR_denun)
                    .addComponent(btn_salir_de, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDenunciaLayout = new javax.swing.GroupLayout(panelDenuncia);
        panelDenuncia.setLayout(panelDenunciaLayout);
        panelDenunciaLayout.setHorizontalGroup(
            panelDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_denuncia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDenunciaLayout.setVerticalGroup(
            panelDenunciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDenunciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_denuncia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Jpanel_reportes.addTab("Reportes de Denuncias    ", panelDenuncia);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jpanel_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(Jpanel_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(Jpanel_reportes1)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(719, 719, 719)
                .addComponent(Jpanel_reportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ch_Cate_AreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_Cate_AreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_Cate_AreaActionPerformed

    private void ch_Cate_AreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ch_Cate_AreaMousePressed
        // TODO add your handling code here:
        if (ch_Cate_Area.isSelected()==true){ComboBox_Area.setEnabled(false);
        }
        else  {ComboBox_Area.setEnabled(true);}
    }//GEN-LAST:event_ch_Cate_AreaMousePressed

    private void btn_salir_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir_cActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_salir_cActionPerformed

    private void btn_genR_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genR_catActionPerformed
        // TODO add your handling code here:
        generarReporteCatedratico();
    }//GEN-LAST:event_btn_genR_catActionPerformed

    private void btn_nueva_consulta_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nueva_consulta_catActionPerformed
    limpiar_cat();       
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_nueva_consulta_catActionPerformed

    private void ch_cat_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ch_cat_nombreMousePressed
        // TODO add your handling code here:
        if (ch_cat_nombre.isSelected()==true){txt_cat_nombre.setEnabled(false);
        }
        else  {txt_cat_nombre.setEnabled(true);

        }
    }//GEN-LAST:event_ch_cat_nombreMousePressed

    private void cb_tipo_denunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipo_denunciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipo_denunciaActionPerformed

    private void ch_tipo_denunciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ch_tipo_denunciaMousePressed
        // TODO add your handling code here:
        if (ch_tipo_denuncia.isSelected()==true){cb_tipo_denuncia.setEnabled(false);
        }
        else  {cb_tipo_denuncia.setEnabled(true);}
    }//GEN-LAST:event_ch_tipo_denunciaMousePressed

    private void btn_salir_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir_deActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_salir_deActionPerformed

    private void btn_geneR_denunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geneR_denunActionPerformed
        // TODO add your handling code here:
        generarReportDenuncia();
    }//GEN-LAST:event_btn_geneR_denunActionPerformed

    private void btn_nueva_consulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nueva_consulta2ActionPerformed
        // TODO add your handling code here:
        limpiarDenuncia();
    }//GEN-LAST:event_btn_nueva_consulta2ActionPerformed

    private void ch_no_denunciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ch_no_denunciaMousePressed
        // TODO add your handling code here:
        if (ch_no_denuncia.isSelected()==true){dch_rep_denuncia.setEnabled(false);
        }
        else  {dch_rep_denuncia.setEnabled(true);}

    }//GEN-LAST:event_ch_no_denunciaMousePressed

    private void btn_salir_alActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir_alActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_salir_alActionPerformed

    private void btn_genR_alActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genR_alActionPerformed
        // Busca con id y set en la tabla
        generarReporteAlumno();
    }//GEN-LAST:event_btn_genR_alActionPerformed

    private void btn_nueva_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nueva_consultaActionPerformed
        // TODO add your handling code here:
        limpiarAlumno();

    }//GEN-LAST:event_btn_nueva_consultaActionPerformed

    private void ch_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_carreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_carreraActionPerformed

    private void ch_carreraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ch_carreraMousePressed
        // TODO add your handling code here:
        if (ch_carrera.isSelected()==true){cb_carrera.setEnabled(false);
        }
        else  {cb_carrera.setEnabled(true);}
    }//GEN-LAST:event_ch_carreraMousePressed

    private void cb_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_carreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_carreraActionPerformed

    private void ch_LugarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ch_LugarMousePressed
        // TODO add your handling code here:
        if (ch_Lugar.isSelected()==true){txt_lugar.setEnabled(false);
        }
        else  {txt_lugar.setEnabled(true);}
    }//GEN-LAST:event_ch_LugarMousePressed

    private void ch_anio1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ch_anio1MousePressed
        // TODO add your handling code here:

        if (ch_anio1.isSelected()==true){Jch_anio.setEnabled(false);
        }
        else  {Jch_anio.setEnabled(true);}

    }//GEN-LAST:event_ch_anio1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox_Area;
    private com.toedter.calendar.JYearChooser Jch_anio;
    private javax.swing.JTabbedPane Jpanel_reportes;
    private javax.swing.JTabbedPane Jpanel_reportes1;
    private javax.swing.JButton btn_genR_al;
    private javax.swing.JButton btn_genR_cat;
    private javax.swing.JButton btn_geneR_denun;
    private javax.swing.JButton btn_nueva_consulta;
    private javax.swing.JButton btn_nueva_consulta2;
    private javax.swing.JButton btn_nueva_consulta_cat;
    private javax.swing.JButton btn_salir_al;
    private javax.swing.JButton btn_salir_c;
    private javax.swing.JButton btn_salir_de;
    private javax.swing.JComboBox cb_carrera;
    private javax.swing.JComboBox cb_tipo_denuncia;
    private javax.swing.JCheckBox ch_Cate_Area;
    private javax.swing.JCheckBox ch_Lugar;
    private javax.swing.JCheckBox ch_anio1;
    private javax.swing.JCheckBox ch_carrera;
    private javax.swing.JCheckBox ch_cat_nombre;
    private javax.swing.JCheckBox ch_no_denuncia;
    private javax.swing.JCheckBox ch_tipo_denuncia;
    private com.toedter.calendar.JDateChooser dch_rep_denuncia;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel panelDenuncia;
    private javax.swing.JPanel panel_Alumnos;
    private javax.swing.JPanel panel_denuncia;
    private javax.swing.JPanel panle_maestro;
    private javax.swing.JTable tabla_alumno;
    private javax.swing.JTable tabla_maestros;
    private javax.swing.JTable tb_Denuncias;
    private javax.swing.JTextField txt_cat_nombre;
    private javax.swing.JTextField txt_lugar;
    // End of variables declaration//GEN-END:variables

      private void mostrarTipoDenuncia() {
       Connection conn = null;     
       String   sql = null;
       ResultSet rs = null;
       Statement  st = null;     
       
       try {
             
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bienestar_estudiantil","root","liberal");
              st = conn.createStatement();
              rs = st.executeQuery ("SELECT nombreTipoDenuncia FROM TipoDenuncia");
     
          while(rs.next()){
               String tmpStrObtenido = rs.getString("nombreTipoDenuncia");
               cb_tipo_denuncia.addItem(tmpStrObtenido);
               
               
           }
          conn.close();
         } catch (Exception e) {
             System.out.println("ERROR: failed to load HSQLDB JDBC driver.");
             e.printStackTrace();
             return;
         }
    }
    
    private void generarReporteAlumno() {
     try {  
         String sql, ag1="", ag2="", ag3="";
         sql="SELECT noCuenta as 'Numero de Cuenta', concat(nombreAlumno,\" \", apellidoAlumno) as 'Nombre Completo', carreraAlumno as 'Carrera', emaiAlumno as 'Correo ELectronico', telefono as 'No Telefonico', lugar_proc_alumno as 'Direccion' from Alumno";
         
         if(ch_anio1.isSelected()==true ||ch_Lugar.isSelected()==true ||ch_carrera.isSelected()==true ){        
         
             if (ch_anio1.isSelected()==true){
         
             ag1=", `noCuenta` like '"+Jch_anio.getYear()+"%' ";
         
            }
            if (ch_Lugar.isSelected()==true){ 
            ag2=", lugar_proc_alumno like '%"+txt_lugar.getText()+"%' ";
            }
            if (ch_carrera.isSelected()==true){ 
            ag3=", carreraAlumno like '"+cb_carrera.getSelectedItem().toString()+"' ";
         }
         sql=sql+" where concat_ws('and'"+ag1+ag2+ag3+")";
             
         }           
          
         operaciones op = new operaciones();
            
            
            
            ResultSet rs = op.ConsultaBase(sql);                  
            
            
            ResultSetMetaData Columnas = rs.getMetaData();
            
            DefaultTableModel alumno=new DefaultTableModel();
            int cantidadColumnas = Columnas.getColumnCount();
            for (int i = 1; i <= cantidadColumnas; i++) {
                    alumno.addColumn(Columnas.getColumnLabel(i)); //Agrega columnas al modelo con el titulo extraido de la metadata
             }
             //Extrae las filas del resultSet y los para al modelo
                while (rs.next()) {
                       Object[] fila = new Object[cantidadColumnas];
                        for (int i = 0; i < cantidadColumnas; i++) {
                                 fila[i]=rs.getObject(i+1);
                        }
                 alumno.addRow(fila); //agregamos al modelo la fila extraida.
                }
                
            tabla_alumno.setModel(alumno);
            
        } catch (SQLException ex) {
            Logger.getLogger(Denuncias.class.getName()).log(Level.SEVERE, null, ex);
        }
       }

    private void mostrarCarrerasAlumno() {
    Connection conn = null;     
       String   sql = null;
       ResultSet rs = null;
       Statement  st = null;     
       
       try {
             
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bienestar_estudiantil","root","liberal");
              st = conn.createStatement();
              rs = st.executeQuery ("SELECT nombreCarrera FROM Carrera");
     
          while(rs.next()){
               String tmpStrObtenido = rs.getString("nombreCarrera");
               cb_carrera.addItem(tmpStrObtenido);
    
               
           }
          conn.close();
         } catch (Exception e) {
             System.out.println("ERROR: failed to load HSQLDB JDBC driver.");
             e.printStackTrace();
             return;
         }
    }

    private void generarReportDenuncia() {
      try {  
         String sql, sql1, ag1="", ag2="";
         sql1="SELECT noDenuncia as 'Numero de Denuncia', fechaDenuncia as 'Fecha de Creacion', tipo_Denuncia as 'Tipo Denunciante- Denunciado', remitido as 'Denunciante', denunciado as 'Denunciado', motivoDenuncia as 'Observaciones' from Denuncia";
         sql=sql1;
         if (ch_no_denuncia.isSelected()==true){
             Date myDate = dch_rep_denuncia.getDate();
             String date=new SimpleDateFormat("yyyy-MM-dd").format(myDate);
             ag1=" `fechaDenuncia` like '"+date+"' ";
             sql=sql1+" where "+ag1;
         }
         if (ch_tipo_denuncia.isSelected()==true){ 
            ag2=" tipo_Denuncia like '"+cb_tipo_denuncia.getSelectedItem().toString()+"' ";
            sql=sql1+" where "+ag2;
            }
         if(ch_no_denuncia.isSelected()==true && ch_tipo_denuncia.isSelected()==true ){        
         
         sql=sql1+" where "+ag1+" and "+ag2;
         }
         
             System.out.println(sql);     
                    
          
         operaciones op = new operaciones();
            
            
            
            ResultSet rs = op.ConsultaBase(sql);                  
            
            
            ResultSetMetaData Columnas = rs.getMetaData();
            
            DefaultTableModel alumno=new DefaultTableModel();
            int cantidadColumnas = Columnas.getColumnCount();
            for (int i = 1; i <= cantidadColumnas; i++) {
                    alumno.addColumn(Columnas.getColumnLabel(i)); //Agrega columnas al modelo con el titulo extraido de la metadata
             }
             //Extrae las filas del resultSet y los para al modelo
                while (rs.next()) {
                       Object[] fila = new Object[cantidadColumnas];
                        for (int i = 0; i < cantidadColumnas; i++) {
                                 fila[i]=rs.getObject(i+1);
                        }
                 alumno.addRow(fila); //agregamos al modelo la fila extraida.
                }
                
            tb_Denuncias.setModel(alumno);
            
        } catch (SQLException ex) {
            Logger.getLogger(Denuncias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void generarReporteCatedratico() {
       String sql="SELECT c.idEmpleado as 'No de Identidad', concat(e.nombreEmpleado,' ', e.apellidoEmpleado) as 'Nombre Completo', v.nombreArea as 'Area',e.emailEmp as 'Correo ELectronico', e.telefonoEmpleado as 'Telefono'FROM Empleado e\n" +
                   "JOIN Catedratico c\n" +"ON e.idEmpleado = c.idEmpleado\n" +"JOIN Area v\n" +"ON c.idArea = v.idArea";
       
       try {  
         String  sql1, ag1="", ag2="";
         sql1=sql;
         
         if (ch_cat_nombre.isSelected()==true){
             String nombre=txt_cat_nombre.getText();
             ag1=" nombreEmpleado like '%"+nombre+"%' or apellidoEmpleado like '%"+nombre+"%'" ;
             sql=sql1+" where "+ag1;
         }
         if (ch_Cate_Area.isSelected()==true){ 
            ag2=" nombreArea='" +ComboBox_Area.getSelectedItem().toString()+"' ";
            
            sql=sql1+" where "+ag2;
            }
         if(ch_cat_nombre.isSelected()==true && ch_Cate_Area.isSelected()==true ){        
         
         sql=sql1+" where "+ag1+" and "+ag2;
         }
         
             System.out.println(sql);     
                    
          
         operaciones op = new operaciones();
            
            
            
            ResultSet rs = op.ConsultaBase(sql);                  
            
            
            ResultSetMetaData Columnas = rs.getMetaData();
            
            DefaultTableModel alumno=new DefaultTableModel();
            int cantidadColumnas = Columnas.getColumnCount();
            for (int i = 1; i <= cantidadColumnas; i++) {
                    alumno.addColumn(Columnas.getColumnLabel(i)); //Agrega columnas al modelo con el titulo extraido de la metadata
             }
             //Extrae las filas del resultSet y los para al modelo
                while (rs.next()) {
                       Object[] fila = new Object[cantidadColumnas];
                        for (int i = 0; i < cantidadColumnas; i++) {
                                 fila[i]=rs.getObject(i+1);
                        }
                 alumno.addRow(fila); //agregamos al modelo la fila extraida.
                }
                
            tabla_maestros.setModel(alumno);
            
        } catch (SQLException ex) {
            Logger.getLogger(Denuncias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void llenarCbMaestro() {
    String sql="SELECT nombreArea FROM Area";
        try {
            operaciones op = new operaciones();
            ResultSet rs=op.ConsultaBase(sql);
            while(rs.next()){
               String tmpStrObtenido = rs.getString("nombreArea");
               ComboBox_Area.addItem(tmpStrObtenido);
                    } 
    
    }   catch (SQLException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void generarReporteAsignatura() {
    String sql="SELECT c.idEmpleado as 'No de Identidad', concat(e.nombreEmpleado,' ', e.apellidoEmpleado) as 'Nombre Completo', v.nombreArea as 'Area',e.emailEmp as 'Correo ELectronico', e.telefonoEmpleado as 'Telefono'FROM Empleado e" +
                   "JOIN Catedratico c" +"ON e.idEmpleado = c.idEmpleado" +"JOIN Area v" +"ON c.idArea = v.idArea";
       
       try {  
         String  sql1, ag1="";
         sql1=sql;
         
         if (ch_cat_nombre.isSelected()==true){
             String nombre=txt_cat_nombre.getText();
             ag1=" nombreEmpleado like '%"+nombre+"%' or apellidoEmpleado like '%"+nombre+"%'" ;
             sql=sql1+" where "+ag1;
         }
         
         
             System.out.println(sql);     
                    
          
         operaciones op = new operaciones();
            
            
            
            ResultSet rs = op.ConsultaBase(sql);                  
            
            
            ResultSetMetaData Columnas = rs.getMetaData();
            
            DefaultTableModel alumno=new DefaultTableModel();
            int cantidadColumnas = Columnas.getColumnCount();
            for (int i = 1; i <= cantidadColumnas; i++) {
                    alumno.addColumn(Columnas.getColumnLabel(i)); //Agrega columnas al modelo con el titulo extraido de la metadata
             }
             //Extrae las filas del resultSet y los para al modelo
                while (rs.next()) {
                       Object[] fila = new Object[cantidadColumnas];
                        for (int i = 0; i < cantidadColumnas; i++) {
                                 fila[i]=rs.getObject(i+1);
                        }
                 alumno.addRow(fila); //agregamos al modelo la fila extraida.
                }
                
            tabla_maestros.setModel(alumno);
            
        } catch (SQLException ex) {
            Logger.getLogger(Denuncias.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }

    private void limpiar_cat() {
        txt_cat_nombre.setText("");
        ComboBox_Area.setSelectedIndex(0);
        txt_cat_nombre.setEnabled(false);
        ComboBox_Area.setEnabled(false);
        ch_cat_nombre.setSelected(false);
        ch_Cate_Area.setSelected(false);
    }

    private void limpiarDenuncia() {
        dch_rep_denuncia.setDateFormatString("");
        cb_tipo_denuncia.setSelectedIndex(0);
        dch_rep_denuncia.setEnabled(false);
        cb_tipo_denuncia.setEnabled(false);
        ch_no_denuncia.setSelected(false);
        ch_tipo_denuncia.setSelected(false);
    }
     private void Cierre(java.awt.event.WindowEvent evt) {                        
        int op = JOptionPane.showConfirmDialog(this, "Seguro que desea salir","Salir",JOptionPane.YES_NO_OPTION);
        if(op==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }
}
   

